# Generated by Django 5.1.4 on 2026-03-24 14:13

import accounts.models.otp
import core.services.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        default=accounts.models.otp.generate_otp, max_length=6
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RESET_PASSWORD", "Reset Password"),
                            ("EMAIL_VERIFICATION", "Email Verification"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, default="en", max_length=20, verbose_name="Language"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_photos/",
                        validators=[core.services.validators.validate_model_image_only],
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("federation", "Sport Federation"),
                            ("club", "Club / Academy"),
                            ("coach", "Coach"),
                            ("referee", "Referee"),
                            ("player", "Player"),
                            ("fan", "Fan / General User"),
                        ],
                        db_index=True,
                        default="fan",
                        max_length=20,
                        verbose_name="User Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Set to False to disable the account (admin action). ",
                        verbose_name="Active",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True once the user has confirmed their email via OTP.",
                        verbose_name="Email Verified",
                    ),
                ),
                (
                    "nationality",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="Nationality"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "club_name",
                    models.CharField(max_length=200, verbose_name="Club Name"),
                ),
                (
                    "club_type",
                    models.CharField(
                        choices=[
                            ("club", "Tennis Club"),
                            ("academy", "Academy"),
                            ("training_center", "Training Center"),
                            ("school", "School / University"),
                            ("other", "Other"),
                        ],
                        default="club",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "founding_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Founding Year"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Registration Number"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="club_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "facility_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Courts/Facilities"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Profile",
                "verbose_name_plural": "Club Profiles",
                "ordering": ["club_name"],
            },
        ),
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Specialization"
                    ),
                ),
                (
                    "coaching_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner / Recreational"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced / Competitive"),
                            ("elite", "Elite / Professional"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="Coaching Level",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="License Number"
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated",
                        verbose_name="Certifications",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach Profile",
                "verbose_name_plural": "Coach Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FanProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        editable=False,
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorite_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fans",
                        to="accounts.clubprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fan_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fan Profile",
                "verbose_name_plural": "Fan Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FederationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "federation_name",
                    models.CharField(max_length=200, verbose_name="Federation Name"),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("tennis", "Tennis"),
                            ("multi_sport", "Multi-Sport"),
                            ("other", "Other"),
                        ],
                        default="tennis",
                        max_length=30,
                        verbose_name="Sport",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "founding_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Founding Year"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Registration Number"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="federation_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federation_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Federation Profile",
                "verbose_name_plural": "Federation Profiles",
                "ordering": ["federation_name"],
            },
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("professional", "Professional"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Skill Level",
                    ),
                ),
                (
                    "ranking",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ranking"
                    ),
                ),
                (
                    "dominant_hand",
                    models.CharField(
                        choices=[
                            ("right", "Right"),
                            ("left", "Left"),
                            ("ambidextrous", "Ambidextrous"),
                        ],
                        default="right",
                        max_length=20,
                        verbose_name="Dominant Hand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Profile",
                "verbose_name_plural": "Player Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefereeProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "referee_level",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("national", "National"),
                            ("international", "International / ITF"),
                        ],
                        default="local",
                        max_length=20,
                        verbose_name="Referee Level",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="License Number"
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated",
                        verbose_name="Certifications",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "itf_badge",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ITF Badge / ID"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referee Profile",
                "verbose_name_plural": "Referee Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
